"use strict";
/**
 * kiro-ts Module Entry Point — KSA-237
 * Re-exports route handlers for integration into http-entry.js.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.ConversionError = exports.mapModel = exports.convertRequest = exports.proxyNonStreaming = exports.proxyStream = exports.writeSSEHeaders = exports.formatSSEEvent = exports.ToolIdMismatchError = exports.ConversationSession = exports.ConversationStore = exports.validateRequest = exports.signRequest = exports.systemVersion = exports.AWS_SDK_VERSION = exports.NODE_VERSION = exports.KIRO_VERSION = exports.resolveAuthRegion = exports.isIdcToken = exports.isTokenExpiringSoon = exports.isTokenExpired = exports.refreshIdcToken = exports.refreshSocialToken = exports.refreshToken = exports.TokenRefreshError = exports.RefreshTokenExpiredError = exports.buildKiroAuthResult = exports.ensureFreshKiroToken = exports.getActiveTokenPath = exports.discoverKiroTokenPath = exports.invalidateApiRegionCache = exports.resolveApiRegionAsync = exports.resolveApiRegion = exports.hasValidCredentials = exports.getGatewayApiKey = exports.getPrivateApiKey = exports.initializeAuth = exports.setCredentialPathOverride = exports.AuthenticationError = exports.resolveAuth = exports.fetchAnthropicModels = exports.ANTHROPIC_FALLBACK_MODELS = exports.AnthropicPassthroughAdapter = exports.KIRO_MODELS = exports.KiroAdapter = exports.buildModelsListResponse = exports.selectAdapter = exports.checkHealth = exports.handleModelsRoute = exports.sendError = exports.handleChatRoute = void 0;
exports.deriveMachineId = exports.normalizeMachineId = exports.resolveMachineId = exports.KiroStreamConverter = exports.crc32 = exports.parseFrame = exports.EventStreamDecoder = exports.mapKiroApiModels = exports.fetchKiroModels = void 0;
var chat_handler_js_1 = require("./chat-handler.js");
Object.defineProperty(exports, "handleChatRoute", { enumerable: true, get: function () { return chat_handler_js_1.handleChatRoute; } });
Object.defineProperty(exports, "sendError", { enumerable: true, get: function () { return chat_handler_js_1.sendError; } });
var models_handler_js_1 = require("./models-handler.js");
Object.defineProperty(exports, "handleModelsRoute", { enumerable: true, get: function () { return models_handler_js_1.handleModelsRoute; } });
var health_checker_js_1 = require("./health-checker.js");
Object.defineProperty(exports, "checkHealth", { enumerable: true, get: function () { return health_checker_js_1.checkHealth; } });
var index_js_1 = require("./adapters/index.js");
Object.defineProperty(exports, "selectAdapter", { enumerable: true, get: function () { return index_js_1.selectAdapter; } });
Object.defineProperty(exports, "buildModelsListResponse", { enumerable: true, get: function () { return index_js_1.buildModelsListResponse; } });
Object.defineProperty(exports, "KiroAdapter", { enumerable: true, get: function () { return index_js_1.KiroAdapter; } });
Object.defineProperty(exports, "KIRO_MODELS", { enumerable: true, get: function () { return index_js_1.KIRO_MODELS; } });
Object.defineProperty(exports, "AnthropicPassthroughAdapter", { enumerable: true, get: function () { return index_js_1.AnthropicPassthroughAdapter; } });
Object.defineProperty(exports, "ANTHROPIC_FALLBACK_MODELS", { enumerable: true, get: function () { return index_js_1.ANTHROPIC_FALLBACK_MODELS; } });
Object.defineProperty(exports, "fetchAnthropicModels", { enumerable: true, get: function () { return index_js_1.fetchAnthropicModels; } });
var auth_resolver_js_1 = require("./auth-resolver.js");
Object.defineProperty(exports, "resolveAuth", { enumerable: true, get: function () { return auth_resolver_js_1.resolveAuth; } });
Object.defineProperty(exports, "AuthenticationError", { enumerable: true, get: function () { return auth_resolver_js_1.AuthenticationError; } });
Object.defineProperty(exports, "setCredentialPathOverride", { enumerable: true, get: function () { return auth_resolver_js_1.setCredentialPathOverride; } });
Object.defineProperty(exports, "initializeAuth", { enumerable: true, get: function () { return auth_resolver_js_1.initializeAuth; } });
Object.defineProperty(exports, "getPrivateApiKey", { enumerable: true, get: function () { return auth_resolver_js_1.getPrivateApiKey; } });
Object.defineProperty(exports, "getGatewayApiKey", { enumerable: true, get: function () { return auth_resolver_js_1.getGatewayApiKey; } });
Object.defineProperty(exports, "hasValidCredentials", { enumerable: true, get: function () { return auth_resolver_js_1.hasValidCredentials; } });
Object.defineProperty(exports, "resolveApiRegion", { enumerable: true, get: function () { return auth_resolver_js_1.resolveApiRegion; } });
Object.defineProperty(exports, "resolveApiRegionAsync", { enumerable: true, get: function () { return auth_resolver_js_1.resolveApiRegionAsync; } });
Object.defineProperty(exports, "invalidateApiRegionCache", { enumerable: true, get: function () { return auth_resolver_js_1.invalidateApiRegionCache; } });
Object.defineProperty(exports, "discoverKiroTokenPath", { enumerable: true, get: function () { return auth_resolver_js_1.discoverKiroTokenPath; } });
Object.defineProperty(exports, "getActiveTokenPath", { enumerable: true, get: function () { return auth_resolver_js_1.getActiveTokenPath; } });
Object.defineProperty(exports, "ensureFreshKiroToken", { enumerable: true, get: function () { return auth_resolver_js_1.ensureFreshKiroToken; } });
Object.defineProperty(exports, "buildKiroAuthResult", { enumerable: true, get: function () { return auth_resolver_js_1.buildKiroAuthResult; } });
Object.defineProperty(exports, "RefreshTokenExpiredError", { enumerable: true, get: function () { return auth_resolver_js_1.RefreshTokenExpiredError; } });
Object.defineProperty(exports, "TokenRefreshError", { enumerable: true, get: function () { return auth_resolver_js_1.TokenRefreshError; } });
var token_refresh_js_1 = require("./token-refresh.js");
Object.defineProperty(exports, "refreshToken", { enumerable: true, get: function () { return token_refresh_js_1.refreshToken; } });
Object.defineProperty(exports, "refreshSocialToken", { enumerable: true, get: function () { return token_refresh_js_1.refreshSocialToken; } });
Object.defineProperty(exports, "refreshIdcToken", { enumerable: true, get: function () { return token_refresh_js_1.refreshIdcToken; } });
Object.defineProperty(exports, "isTokenExpired", { enumerable: true, get: function () { return token_refresh_js_1.isTokenExpired; } });
Object.defineProperty(exports, "isTokenExpiringSoon", { enumerable: true, get: function () { return token_refresh_js_1.isTokenExpiringSoon; } });
Object.defineProperty(exports, "isIdcToken", { enumerable: true, get: function () { return token_refresh_js_1.isIdcToken; } });
Object.defineProperty(exports, "resolveAuthRegion", { enumerable: true, get: function () { return token_refresh_js_1.resolveAuthRegion; } });
var kiro_config_js_1 = require("./kiro-config.js");
Object.defineProperty(exports, "KIRO_VERSION", { enumerable: true, get: function () { return kiro_config_js_1.KIRO_VERSION; } });
Object.defineProperty(exports, "NODE_VERSION", { enumerable: true, get: function () { return kiro_config_js_1.NODE_VERSION; } });
Object.defineProperty(exports, "AWS_SDK_VERSION", { enumerable: true, get: function () { return kiro_config_js_1.AWS_SDK_VERSION; } });
Object.defineProperty(exports, "systemVersion", { enumerable: true, get: function () { return kiro_config_js_1.systemVersion; } });
var sigv4_signer_js_1 = require("./sigv4-signer.js");
Object.defineProperty(exports, "signRequest", { enumerable: true, get: function () { return sigv4_signer_js_1.signRequest; } });
var request_validator_js_1 = require("./request-validator.js");
Object.defineProperty(exports, "validateRequest", { enumerable: true, get: function () { return request_validator_js_1.validateRequest; } });
var conversation_store_js_1 = require("./conversation-store.js");
Object.defineProperty(exports, "ConversationStore", { enumerable: true, get: function () { return conversation_store_js_1.ConversationStore; } });
Object.defineProperty(exports, "ConversationSession", { enumerable: true, get: function () { return conversation_store_js_1.ConversationSession; } });
Object.defineProperty(exports, "ToolIdMismatchError", { enumerable: true, get: function () { return conversation_store_js_1.ToolIdMismatchError; } });
var stream_proxy_js_1 = require("./stream-proxy.js");
Object.defineProperty(exports, "formatSSEEvent", { enumerable: true, get: function () { return stream_proxy_js_1.formatSSEEvent; } });
Object.defineProperty(exports, "writeSSEHeaders", { enumerable: true, get: function () { return stream_proxy_js_1.writeSSEHeaders; } });
Object.defineProperty(exports, "proxyStream", { enumerable: true, get: function () { return stream_proxy_js_1.proxyStream; } });
Object.defineProperty(exports, "proxyNonStreaming", { enumerable: true, get: function () { return stream_proxy_js_1.proxyNonStreaming; } });
var kiro_converter_js_1 = require("./kiro-converter.js");
Object.defineProperty(exports, "convertRequest", { enumerable: true, get: function () { return kiro_converter_js_1.convertRequest; } });
Object.defineProperty(exports, "mapModel", { enumerable: true, get: function () { return kiro_converter_js_1.mapModel; } });
Object.defineProperty(exports, "ConversionError", { enumerable: true, get: function () { return kiro_converter_js_1.ConversionError; } });
var kiro_models_client_js_1 = require("./kiro-models-client.js");
Object.defineProperty(exports, "fetchKiroModels", { enumerable: true, get: function () { return kiro_models_client_js_1.fetchKiroModels; } });
Object.defineProperty(exports, "mapKiroApiModels", { enumerable: true, get: function () { return kiro_models_client_js_1.mapKiroApiModels; } });
var event_stream_parser_js_1 = require("./event-stream-parser.js");
Object.defineProperty(exports, "EventStreamDecoder", { enumerable: true, get: function () { return event_stream_parser_js_1.EventStreamDecoder; } });
Object.defineProperty(exports, "parseFrame", { enumerable: true, get: function () { return event_stream_parser_js_1.parseFrame; } });
Object.defineProperty(exports, "crc32", { enumerable: true, get: function () { return event_stream_parser_js_1.crc32; } });
var kiro_stream_js_1 = require("./kiro-stream.js");
Object.defineProperty(exports, "KiroStreamConverter", { enumerable: true, get: function () { return kiro_stream_js_1.KiroStreamConverter; } });
var machine_id_js_1 = require("./machine-id.js");
Object.defineProperty(exports, "resolveMachineId", { enumerable: true, get: function () { return machine_id_js_1.resolveMachineId; } });
Object.defineProperty(exports, "normalizeMachineId", { enumerable: true, get: function () { return machine_id_js_1.normalizeMachineId; } });
Object.defineProperty(exports, "deriveMachineId", { enumerable: true, get: function () { return machine_id_js_1.deriveMachineId; } });
//# sourceMappingURL=index.js.map